/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.GridLayout;
import lfa.Main;

/**
 *
 * @author YiazmaT
 */
public class MaquinaDeNorma extends javax.swing.JPanel {
    private Main pai;
    /**
     * Creates new form MáquinadeNorma
     */
    public MaquinaDeNorma(Main pai) {
        initComponents();
        this.pai=pai;
        
        int quantidadeLinhas = 2;
        GridLayout gl = new GridLayout(quantidadeLinhas, 1);
        jPanel1.setLayout(gl);
        
        Celula celulas1[] = new Celula[2];
        Celula celulas2[] = new Celula[2];
        celulas1[0] = new Celula("A", 0, 2);
        celulas1[1] = new Celula("B", 0, 3);
        celulas2[0] = new Celula("A", 0, 2);
        celulas2[1] = new Celula("B", 0, 3);
        Linha linha1 = new Linha(2, celulas1);
        Linha linha2 = new Linha(2, celulas2);
        
        jPanel1.add(linha1);
        jPanel1.add(linha2);
        
        jScrollPane2.revalidate();
        jScrollPane2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Passo a Passo da Execução"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
