/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.Color;
import java.awt.GridLayout;

/**
 *
 * @author YiazmaT
 */
public class MT_MediumPanel extends javax.swing.JPanel {
    private MT_SmallPanel panels[];
    private int n;
    /**
     * Creates new form MT_MediumPanel
     */
    public MT_MediumPanel(int n) {
        initComponents();
        this.n = n;
        //jLabel1.setText("Test "+numTest);
        panels = new MT_SmallPanel[n+1];
        jPanel1.setLayout(new GridLayout(1,n+1));
        
        for(int i=0;i<n;i++){
            MT_SmallPanel s = new MT_SmallPanel(true);
            jPanel1.add(s);
            panels[i] = s;
        }
        MT_SmallPanel s = new MT_SmallPanel(false);
        jPanel1.add(s);
        panels[n]= s;
        
        jPanel1.revalidate();
        jScrollPane1.revalidate();
        jPanel1.repaint();
    }

    public String[] getLines(){
        String linhas[] = new String[n];
        for(int i=0;i<n;i++){
            linhas[i] = panels[i].getTexto();
        }
        
        return linhas;
    }
    
    public void setLines(String linhas[], boolean accepted){
        if(accepted){
            panels[n].setTexto("Aceita");
            panels[n].setBackground(Color.green);
        }
        else{
            panels[n].setBackground(Color.red);
            panels[n].setTexto("Rejeitada");
        }
        
        for(int i=0;i<n;i++){
            panels[i].setTexto(linhas[i]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
