/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author mortz
 */
public class ResultadoByStepTuring extends javax.swing.JDialog {

    private ViewPanel view;
    private ViewPanel base;
    private String cadeiaLida = "";
    private ArrayList<Integer> caminho;
    private ArrayList<Integer> posLeitor;
    private ArrayList<String> estadosFita;
    private int estadoSelecionado;
    private int instante=0;
    
    public ResultadoByStepTuring(java.awt.Frame parent, boolean modal,ViewPanel base,ArrayList<Integer> caminho, ArrayList<Integer> posLeitor, ArrayList<String> estadoFita) {
        super(parent, modal);
        initComponents();
        view = (ViewPanel)jPanel1;
        this.base = base;
    
        view.estados = base.estados;
        view.trans = base.trans;
        
        this.caminho = caminho;
        this.posLeitor = posLeitor;
        this.estadosFita = estadoFita;
        estadoSelecionado= caminho.get(0);
        caminho.remove(0);
        view.estados.get(estadoSelecionado).setSelecionado(true);
        
        view.setPreferredSize(base.getPreferredSize());
        jScrollPane1.revalidate(); 
        view.cleanImage();
        view.repaint();
        jTextPane1.setContentType("text/html");
        atualizarFita(estadosFita.get(0), posLeitor.get(0));
        estadosFita.remove(0);
        posLeitor.remove(0);
        jTextPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new ViewPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Proximo Passo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Fita:");

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(instante == caminho.size()){
            JOptionPane.showMessageDialog(this, "A cadeia já foi reconhecida");
        }else{
            view.estados.get(estadoSelecionado).setSelecionado(false);
            estadoSelecionado = caminho.get(instante);
            String estadoFita = estadosFita.get(instante);
            int indexLeitura = posLeitor.get(instante);
            view.estados.get(estadoSelecionado).setSelecionado(true);
            instante++;
            
            atualizarFita(estadoFita,indexLeitura);
            
            view.cleanImage();
            view.repaint();
            jScrollPane1.repaint();
            jTextPane1.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        view.estados.get(estadoSelecionado).setSelecionado(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        view.estados.get(estadoSelecionado).setSelecionado(false);
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void atualizarFita(String estadoFita, int indexLeitura) {
        String fita;
//        if(indexLeitura < 0 || indexLeitura >= estadoFita.length())fita = estadoFita;
//        else{
//            fita = "<html>" + estadoFita.substring(0, indexLeitura) + "<u>" + estadoFita.substring(indexLeitura,indexLeitura+1) + "</u>";
//            if(indexLeitura+1==estadoFita.length())fita+="</html>";
//            else fita+= estadoFita.substring(indexLeitura+1) + "</html>";
//        }
        fita = "<html>";
        if(indexLeitura<0){
            fita+="<u>_</u>";
            for(int i=indexLeitura+1;i<0;i++)fita+=" ";
            fita+=estadoFita;
        }
        else if(indexLeitura<estadoFita.length()){
            fita+=estadoFita.substring(0,indexLeitura);
            fita+= "<u>" + estadoFita.substring(indexLeitura, indexLeitura+1) + "</u>";
            fita+=estadoFita.substring(indexLeitura+1);
        }
        else{
            fita+=estadoFita;
            for(int i=estadoFita.length();i<indexLeitura;i++)fita+=" ";
            fita+="<u>_</u>";
        }
        fita+="</html>";
        jTextPane1.setText(fita);
    }
}
